import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import projectsData from './src/data/projects.json';

// Generate sidebar items for a project based on its sections
function generateProjectSidebar(projectId: string, projectTitle: string, sections: Array<{id: string; label: string; folder: string}>) {
  return [
    {
      type: 'category' as const,
      label: projectTitle,
      collapsed: false,
      link: { type: 'doc' as const, id: `${projectId}/README` },
      items: sections.map(section => ({
        type: 'category' as const,
        label: section.label,
        items: [{ type: 'autogenerated' as const, dirName: `${projectId}/${section.folder}` }],
      })),
    },
  ];
}

// Build sidebars dynamically from projects.json
const sidebars: SidebarsConfig = {};

// Generate sidebar for each project
projectsData.projects.forEach(project => {
  sidebars[project.sidebar] = generateProjectSidebar(
    project.id,
    project.title,
    project.sections
  );
});

// Add resources sidebar
sidebars[projectsData.resources.sidebar] = [
  {
    type: 'category',
    label: projectsData.resources.title,
    collapsed: false,
    link: { type: 'doc', id: `${projectsData.resources.id}/README` },
    items: [{ type: 'autogenerated', dirName: projectsData.resources.id }],
  },
];

export default sidebars;
